apiVersion: v1
kind: Namespace
metadata:
  name: plagiarism-app
---
# ---------------- BACKEND ----------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: plagiarism-backend
  namespace: plagiarism-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plagiarism-backend
  template:
    metadata:
      labels:
        app: plagiarism-backend
    spec:
      containers:
        - name: backend
          image: plagiarism-backend:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://db-service:5432/verify
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_PASSWORD
              value: admin
            - name: SERVER_PORT
              value: "8081"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: plagiarism-app
spec:
  type: ClusterIP
  selector:
    app: plagiarism-backend
  ports:
    - port: 8080
      targetPort: 8081
---
# ---------------- POSTGRESQL ----------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: plagiarism-db
  namespace: plagiarism-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plagiarism-db
  template:
    metadata:
      labels:
        app: plagiarism-db
    spec:
      containers:
        - name: db
          image: postgres:17
          env:
            - name: POSTGRES_PASSWORD
              value: admin
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_DB
              value: verify
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: db-service
  namespace: plagiarism-app
spec:
  type: ClusterIP
  selector:
    app: plagiarism-db
  ports:
    - port: 5432
      targetPort: 5432
---
# ---------------- FRONTEND ----------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: plagiarism-frontend
  namespace: plagiarism-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plagiarism-frontend
  template:
    metadata:
      labels:
        app: plagiarism-frontend
    spec:
      containers:
        - name: frontend
          image: plagiarism-frontend:1.0
          imagePullPolicy: Never
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: plagiarism-app
spec:
  type: ClusterIP
  selector:
    app: plagiarism-frontend
  ports:
    - port: 80
      targetPort: 80
---
# ---------------- INGRESS ----------------
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: plagiarism-ingress
  namespace: plagiarism-app
spec:
  rules:
    - host: app.local
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: backend-service
                port:
                  number: 8080
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-service
                port:
                  number: 80
